froide_legalaction/urls.py
from django.urls import include, path
from django.utils.translation import pgettext_lazy

from .views import (
    KlageautomatAnswerEditView,
    KlageautomatAnswerHTMLDownloadView,
    KlageautomatAnswerPDFDownloadView,
    KlageautomatAnswerWordDownloadView,
    KlageautomatInfoPage,
    KlageAutomatWizard,
    LegalDecisionCreateView,
    LegalDecisionDetailView,
    LegalDecisionIncompleteListView,
    LegalDecisionIncompleteUpdateView,
    LegalDecisionListView,
    request_form_page,
    thanks_page,
)

urlpatterns = [
    path(
        pgettext_lazy("url part", "propose/"),
        request_form_page,
        name="legalaction-index",
    ),
    path(
        pgettext_lazy("url part", "thanks/"),
        thanks_page,
        name="legalaction-thanks",
    ),
    path(
        pgettext_lazy("url part", "request/<int:pk>/"),
        request_form_page,
        name="legalaction-request_form",
    ),
    path(
        pgettext_lazy("url part", "klageautomat/info/request/<int:pk>/"),
        KlageautomatInfoPage.as_view(),
        name="klageautomat-info",
    ),
    path(
        pgettext_lazy("url part", "klageautomat/request/<int:pk>/"),
        KlageAutomatWizard.as_view(),
        name="klageautomat-form_wizard",
    ),
    path(
        pgettext_lazy("url part", "klageautomat/request/<int:pk>/answer/"),
        KlageautomatAnswerEditView.as_view(),
        name="klageautomat-edit-answer",
    ),
    path(
        pgettext_lazy("url part", "klageautomat/request/<int:pk>/answer/pdf-download/"),
        KlageautomatAnswerPDFDownloadView.as_view(),
        name="klageautomat-pdf-download-answer",
    ),
    path(
        pgettext_lazy(
            "url part", "klageautomat/request/<int:pk>/answer/word-download/"
        ),
        KlageautomatAnswerWordDownloadView.as_view(),
        name="klageautomat-word-download-answer",
    ),
    path(
        pgettext_lazy(
            "url part", "klageautomat/request/<int:pk>/answer/html-download/"
        ),
        KlageautomatAnswerHTMLDownloadView.as_view(),
        name="klageautomat-html-download-answer",
    ),
    path("klageautomat/admin/", include("legal_advice_builder.urls")),
    path(
        pgettext_lazy("url part", "legal-decisions/"),
        LegalDecisionListView.as_view(),
        name="legal-decision-list",
    ),
    path(
        pgettext_lazy("url part", "legal-decisions-incomplete/"),
        LegalDecisionIncompleteListView.as_view(),
        name="legal-decision-list-incomplete",
    ),
    path(
        pgettext_lazy("url part", "legal-decisions-incomplete/<int:pk>/"),
        LegalDecisionIncompleteUpdateView.as_view(),
        name="legal-decision-incomplete-update",
    ),
    path(
        pgettext_lazy("url part", "legal-decisions/create/"),
        LegalDecisionCreateView.as_view(),
        name="legal-decision-create",
    ),
    path(
        pgettext_lazy("url part", "legal-decisions/<int:pk>/"),
        LegalDecisionDetailView.as_view(),
        name="legal-decision-detail",
    ),
]

froide_legalaction/models/decision.py
import functools

from django.conf import settings
from django.contrib.postgres.search import SearchVector, SearchVectorField
from django.db import models
from django.db.models import Q
from django.template import defaultfilters
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from parler.managers import TranslatableManager
from parler.models import TranslatableModel, TranslatedFields

from froide.document.models import Document
from froide.publicbody.models import FoiLaw, PublicBody


class LegalDecisionTagManager(TranslatableManager):
    def get_queryset(self):
        return super().get_queryset().prefetch_related("translations")


class LegalDecisionTag(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(verbose_name=_("name"), unique=False, max_length=100),
        slug=models.SlugField(verbose_name=_("slug"), unique=False, max_length=100),
    )

    objects = LegalDecisionTagManager()

    def __str__(self):
        return self.name


class LegalDecisionManager(TranslatableManager):
    def get_queryset(self):
        return super().get_queryset().prefetch_related("translations")

    def all_incomplete(self):
        return self.filter(
            Q(reference="")
            | Q(date__isnull=True)
            | Q(decision_type="")
            | Q(translations__abstract="")
            | Q(foi_court__isnull=True)
        )

    def get_search_lang(self, language):
        if language == "de":
            return "german"
        elif language == "en":
            return "english"
        return "simple"

    def get_search_vector(self, language):
        SEARCH_LANG = self.get_search_lang(language)
        fields = [
            ("search_text", "A"),
        ]
        return functools.reduce(
            lambda a, b: a + b,
            [SearchVector(f, weight=w, config=SEARCH_LANG) for f, w in fields],
        )

    def update_search_index(self, qs=None):
        from froide_legalaction.models import LegalDecisionTranslation

        if qs is None:
            qs = self.get_queryset()
        for decision in qs:
            decision.generate_search_texts()
        translations = LegalDecisionTranslation.objects.all()
        languages = [entry.get("code") for entry in settings.PARLER_LANGUAGES.get(1)]
        for language in languages:
            translations_for_lang = translations.filter(language_code=language)
            search_vector = self.get_search_vector(language)
            translations_for_lang.update(search_vector=search_vector)


class LegalDecision(TranslatableModel):
    class LegalDecisionTypes(models.TextChoices):
        COURT_DECISION = "court_decision", _("Court Decision")
        COURT_RULING = "court_ruling", _("Court Ruling")
        COURT_ORDER = "court_order", _("Court Order")
        COURT_NOTICE = "court_notice", _("Court Notice")

    slug = models.SlugField(
        max_length=255, blank=True, null=True, unique=True, verbose_name=_("Slug")
    )
    translations = TranslatedFields(
        title=models.CharField(max_length=500, blank=True, verbose_name=_("Title")),
        abstract=models.TextField(blank=True, verbose_name=_("Abstract")),
        guiding_principle=models.TextField(
            blank=True, verbose_name=_("Guiding principle")
        ),
        fulltext=models.TextField(blank=True, verbose_name=_("Full text")),
        court=models.CharField(
            max_length=500, blank=True, verbose_name=_("Name of Court")
        ),
        law=models.CharField(max_length=500, blank=True, verbose_name=_("Law")),
        search_text=models.TextField(blank=True),
        search_vector=SearchVectorField(default="", editable=False),
    )

    tags = models.ManyToManyField(LegalDecisionTag, blank=True)
    decision_type = models.CharField(
        verbose_name=_("Decision Type"),
        choices=LegalDecisionTypes.choices,
        max_length=20,
        blank=True,
    )

    date = models.DateField(blank=True, null=True, verbose_name=_("Date"))
    outcome = models.CharField(max_length=500, blank=True, verbose_name=_("Outcome"))
    reference = models.CharField(
        max_length=200, blank=True, verbose_name=_("docket number")
    )
    ecli = models.CharField(
        max_length=100,
        blank=True,
        null=True,
        unique=True,
        verbose_name=_("European Case Law Identifier"),
    )
    paragraphs = models.JSONField(
        default=list, blank=True, verbose_name=_("Paragraphs")
    )
    source_url = models.URLField(blank=True, verbose_name=_("Source URL"))
    source_data = models.JSONField(blank=True, null=True)

    foi_lawsuit = models.ForeignKey(
        "froide_legalaction.Lawsuit",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name=_("Lawsuit"),
    )
    foi_document = models.ForeignKey(
        Document,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name=_("Document"),
    )
    foi_court = models.ForeignKey(
        PublicBody,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="pb_legaldecisions",
        verbose_name=_("Link to Court"),
    )
    foi_laws = models.ManyToManyField(
        FoiLaw, related_name="legal_decisions", blank=True, verbose_name=_("Laws")
    )

    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="created_legaldecisions",
    )

    objects = LegalDecisionManager()

    def __str__(self):
        return "{}".format(self.reference)

    def get_absolute_url(self):
        return reverse("legaldecision:detail", kwargs={"pk": self.pk})

    @property
    def formatted_date(self):
        return defaultfilters.date(self.date, "DATE_FORMAT")

    @property
    def generated_title(self):
        if self.decision_type and self.court_name:
            if self.date:
                return _("{} of {} on {}").format(
                    self.get_decision_type_display(),
                    self.court_name,
                    self.formatted_date,
                )
            return _("{} of {}").format(
                self.get_decision_type_display(), self.court_name
            )
        if self.foi_document:
            return self.foi_document.title
        return self.reference

    @property
    def court_name(self):
        if self.foi_court:
            return self.foi_court.name
        return self.court

    @property
    def law_name(self):
        if self.foi_laws.all():
            return ", ".join([foi_law.name for foi_law in self.foi_laws.all()])
        return self.law

    def abstract_is_set(self):
        try:
            self.abstract
            return not self.abstract == ""
        except self.DoesNotExist:
            return False

    def court_is_set(self):
        if not self.foi_court:
            try:
                self.court
                return True
            except self.DoesNotExist:
                return False
        return True

    @property
    def fields_incomplete(self):
        from froide_legalaction.models import LegalDecisionTranslation

        relevant_fields = [
            "reference",
            "date",
            "abstract",
            "foi_court",
            "decision_type",
        ]
        res = []

        fields = self._meta.fields
        translated_fields = LegalDecisionTranslation._meta.get_fields()
        all_fields = fields + translated_fields

        for field in all_fields:
            is_relevant = field.name in relevant_fields
            has_field = hasattr(self, field.name)
            if is_relevant:
                if has_field and not getattr(self, field.name):
                    res.append(str(field.verbose_name))
                elif not has_field:
                    res.append(str(field.verbose_name))
        if not self.foi_laws.all():
            res.append(str(_("Laws")))
        return ", ".join(res)

    def generate_search_texts(self):
        tags = self.tags.all()
        for translation in self.translations.all():
            fulltext = ""
            if translation.fulltext:
                fulltext = translation.fulltext
            tag_string = " ".join(
                [
                    tag.translations.filter(
                        language_code=translation.language_code
                    ).values_list("name", flat=True)[0]
                    for tag in tags
                ]
            )
            text = "{} {} {} {} {}".format(
                self.reference,
                translation.law,
                translation.abstract,
                fulltext,
                tag_string,
            )
            translation.search_text = text
            translation.save()

froide_legalaction/templates/froide_legalaction/base.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "Propose a FOI law suit" %}{% endblock %}

{% block body %}
<div class="container mb-5 mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      {% block main %}{% endblock %}
    </div>
  </div>
</div>
{% endblock %}

froide_legalaction/templates/froide_legalaction/base_embed.html
{% extends "base.html" %}

{% block body_tag %}
{% block content %}{% endblock %}
{% endblock %}

froide_legalaction/templates/froide_legalaction/form.html
{% extends base_template %}

{% load i18n %}
{% load form_helper %}

{% block main %}
<h3>{% trans "Propose a FOI law suit" %}</h3>
<p>
  {% blocktrans %}
    Please fill out the form below to propose a law suit for your FOI request.
  {% endblocktrans %}
</p>

{% block content %}
<form class="form-horizontal" method="post" action=""{% if form.is_multipart %} enctype="multipart/form-data"{% endif %}>
  {% csrf_token %}
  {% render_form form %}
  <button type="submit" class="btn btn-primary btn-lg float-end">
    {% blocktrans %}Submit{% endblocktrans %}
  </button>
</form>

{% include "_frontend.html" with entry_point="publicbody.js" %}
{% endblock %}

{% endblock %}

froide_legalaction/templates/froide_legalaction/legaldecision_create.html
{% extends "base.html" %}
{% load form_helper block_helper i18n %}

{% block title %}{% translate 'Create legal decision' %}{% endblock %}

{% block body %}
<div class="bg-body-tertiary">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item active"><a href="{% url 'legal-decision-list' %}">{% translate 'Legal Decisions' %}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{% translate 'Add Legal Decisions' %}</li>
          </ol>
        </nav>
      </div>
    </div>

    <div class="row py-3">
      <div class="col-8">
        <h2 class="h5">{% translate 'Add Legal Decisions' %}</h2>
        <form method="post" class="py-5">
          {% csrf_token %}
          {% for field in form %}
            {% render_field field %}
          {% endfor %}
          <input class="btn btn-primary btn-sm float-end" type="submit" value="{% translate 'Submit' %}">
        </form>
      </div>
    </div>

  </div>
</div>

{% addtoblock "css" %}
  {{ form.media.css }}
{% endaddtoblock %}

{% addtoblock "js" %}
  {{ form.media.js }}
{% endaddtoblock %}

{% endblock %}

froide_legalaction/templates/froide_legalaction/legaldecision_detail.html
{% extends "base.html" %}
{% load form_helper block_helper i18n %}
{% load static %}
{% load filingcabinet %}
{% load markup %}

{% block title %}{{ object.generated_title }}{% endblock %}

{% block body %}
<div class="bg-body-tertiary">
  <div class="container">
    <div class="row justify-content-left">
      <div class="col-md-8">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item active"><a href="{% url 'legal-decision-list' %}">{% translate 'Legal Decisions' %}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ object.title|truncatechars:50 }}</li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>

<div class="bg-body-tertiary pt-3">
  <div class="container">
    <div class="row">
      <div class="col-md-3 mb-3">
        <div class="mb-3 mt-0 {% if not form %} sticky-top{% endif %}">
          <h3 class="h5">{% translate 'Information' %}</h3>
          {% if not form %}
          <dl>
            {% if object.reference %}
              <dt>{% translate 'reference' %}</dt>
              <dd class="user-select-all">{{ object.reference }}</dd>
            {% endif %}

            {% if object.ecli %}
              <dt><abbr title="{% translate 'European Case Law Identifier' %}">ECLI</abbr></dt>
              <dd><code class="user-select-all">{{ object.ecli }}</code></dd>
            {% endif %}


            {% if object.date %}
              <dt>{% translate 'date' %}</dt>
              <dd>{{ object.date }}</dd>
            {% endif %}

            {% if object.foi_court %}
              <dt>{% translate 'court' %}</dt>
              <dd>
                <a href="{{ object.foi_court.get_absolute_url }}">{{ object.foi_court }}</a>
              </dd>
            {% elif object.court_name %}
              <dt>{% translate 'court' %}</dt>
              <dd>
                {{ object.court_name }}
              </dd>
            {% endif %}

            {% if object.law_name %}
              <dt>{% translate 'law' %}</dt>
              <dd>{{ object.law_name }}</dd>
            {% endif %}
          </dl>
          {% endif %}

          {% if object.source_url %}
            <a href="{{ object.source_url }}" rel="noopener">
              {# Translators: link to source of legal decision #}
              {% translate 'Source' %}
            </a>
          {% endif %}

          {% if form %}
          <form method="post">
            {% csrf_token %}
            {% for field in form %}
              {% render_field field horizontal=False %}
            {% endfor %}
            <button class="btn btn-primary btn-sm float-end" type="submit">{% translate 'submit' %}</button>
            {% if has_next %}
            <button class="btn btn-primary btn-sm float-end me-2" type="submit" name="next">{% translate 'submit and next' %}</button>
            {% endif %}
          </form>
          {% endif %}
        </div>
      </div>
      <div class="col-md-9 mb-3">
        {% include "froide_legalaction/includes/_legal_decision.html" %}
        {% if object.foi_document %}
          {% get_pdf_viewer object.foi_document %}

          {% include "_frontend.html" with entry_point="filingcabinet.js" %}
        {% elif object.fulltext %}
          <div class="bg-body shadow-gray p-3 mb-4">
            {{ object.fulltext|markdown }}
          </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>

{% addtoblock "css" %}
  {{ form.media.css }}
{% endaddtoblock %}

{% addtoblock "js" %}
  {{ form.media.js }}
{% endaddtoblock %}

{% endblock %}

froide_legalaction/templates/froide_legalaction/legaldecision_list.html
{% extends "base.html" %}
{% load form_helper block_helper i18n %}

{% block title %}{% translate 'Legal Decisions' %}{% endblock %}

{% block body %}
<div class="bg-body-tertiary pt-5 pb-2">
  <div class="container">
    <div class="pb-4">
      {% if perms.froide_legalaction.change_legaldecision %}
        <a class="btn btn-primary float-end ms-2" href="{% url 'legal-decision-list-incomplete' %}">{% translate 'update incomplete decisions' %}</a>
      {% endif %}

      {% if perms.froide_legalaction.add_legaldecision %}
        <a class="btn btn-primary float-end" href="{% url 'legal-decision-create' %}">{% translate 'Add decisions' %}</a>
      {% endif %}

      <h1>{% translate 'Legal Decisions' %}</h1>
      <p>{% translate 'Decisions and judgements in the field of freedom of information' %}</p>
    </div>
    <div class="row">
      <div class="col-md-12">
        <form method="get">
          <div class="input-group my-2">
            {{ filter.form.quick_search }}
            <button class="btn btn-primary" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="bg-body-tertiary py-3">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <div class="mb-3 mt-0">
          <h3 class="h5">{% translate 'Refine your query' %}</h3>
          {% if selected_filters %}
            <h6>{% translate 'Currently selected:' %}</h6>
            <ul class="list-unstyled">
            {% for name, url in selected_filters %}
              <li>
                <a href="?{{ url }}">
                  <small>{{ name }} <i class="fa fa-times" aria-hidden="true"></i></small>
                </a>
              </li>
            {% endfor %}
            </ul>
          {% endif %}
          <form method="get">
            <ul class="list-unstyled">
              {% for field in filter.form.visible_fields %}
                {% if not field.name == "quick_search" %}
                <li>
                  <div class="filter__field my-3">
                    {% render_field field horizontal=False %}
                  </div>
                </li>
                {% endif %}
              {% endfor %}
            </ul>
          </form>
        </div>
      </div>

      <div class="col-md-9">
        {% if result.paginator.count %}
          {% include "froide_legalaction/includes/pagination.html" with page_obj=result %}
        {% endif %}

        {% for decision in result %}
          {% include "froide_legalaction/includes/_legal_decision.html" with object=decision %}
        {% endfor %}

        {% if result.paginator.count %}
          {% include "froide_legalaction/includes/pagination.html" with page_obj=result %}
        {% endif %}

      </div>
    </div>
  </div>
</div>

{% addtoblock "css" %}
{{ filter.form.media.css }}
{% endaddtoblock %}

{% addtoblock "js" %}
{{ filter.form.media.js }}
{% endaddtoblock %}

{% endblock %}

froide_legalaction/templates/froide_legalaction/thanks.html
{% extends base_template %}

{% load i18n %}

{% block main %}
<h3>{% trans "Thanks for submitting" %}</h3>

<p>
  Wir melden uns innerhalb einer Woche bei Ihnen.
</p>
{% endblock %}