froide_legalaction/urls.py
from django.urls import include, path
from django.utils.translation import pgettext_lazy

from .views import (
    KlageautomatAnswerEditView,
    KlageautomatAnswerHTMLDownloadView,
    KlageautomatAnswerPDFDownloadView,
    KlageautomatAnswerWordDownloadView,
    KlageautomatInfoPage,
    KlageAutomatWizard,
    LegalDecisionCreateView,
    LegalDecisionDetailView,
    LegalDecisionIncompleteListView,
    LegalDecisionIncompleteUpdateView,
    LegalDecisionListView,
    request_form_page,
    thanks_page,
)

urlpatterns = [
    path(
        pgettext_lazy("url part", "propose/"),
        request_form_page,
        name="legalaction-index",
    ),
    path(
        pgettext_lazy("url part", "thanks/"),
        thanks_page,
        name="legalaction-thanks",
    ),
    path(
        pgettext_lazy("url part", "request/<int:pk>/"),
        request_form_page,
        name="legalaction-request_form",
    ),
    path(
        pgettext_lazy("url part", "klageautomat/info/request/<int:pk>/"),
        KlageautomatInfoPage.as_view(),
        name="klageautomat-info",
    ),
    path(
        pgettext_lazy("url part", "klageautomat/request/<int:pk>/"),
        KlageAutomatWizard.as_view(),
        name="klageautomat-form_wizard",
    ),
    path(
        pgettext_lazy("url part", "klageautomat/request/<int:pk>/answer/"),
        KlageautomatAnswerEditView.as_view(),
        name="klageautomat-edit-answer",
    ),
    path(
        pgettext_lazy("url part", "klageautomat/request/<int:pk>/answer/pdf-download/"),
        KlageautomatAnswerPDFDownloadView.as_view(),
        name="klageautomat-pdf-download-answer",
    ),
    path(
        pgettext_lazy(
            "url part", "klageautomat/request/<int:pk>/answer/word-download/"
        ),
        KlageautomatAnswerWordDownloadView.as_view(),
        name="klageautomat-word-download-answer",
    ),
    path(
        pgettext_lazy(
            "url part", "klageautomat/request/<int:pk>/answer/html-download/"
        ),
        KlageautomatAnswerHTMLDownloadView.as_view(),
        name="klageautomat-html-download-answer",
    ),
    path("klageautomat/admin/", include("legal_advice_builder.urls")),
    path(
        pgettext_lazy("url part", "legal-decisions/"),
        LegalDecisionListView.as_view(),
        name="legal-decision-list",
    ),
    path(
        pgettext_lazy("url part", "legal-decisions-incomplete/"),
        LegalDecisionIncompleteListView.as_view(),
        name="legal-decision-list-incomplete",
    ),
    path(
        pgettext_lazy("url part", "legal-decisions-incomplete/<int:pk>/"),
        LegalDecisionIncompleteUpdateView.as_view(),
        name="legal-decision-incomplete-update",
    ),
    path(
        pgettext_lazy("url part", "legal-decisions/create/"),
        LegalDecisionCreateView.as_view(),
        name="legal-decision-create",
    ),
    path(
        pgettext_lazy("url part", "legal-decisions/<int:pk>/"),
        LegalDecisionDetailView.as_view(),
        name="legal-decision-detail",
    ),
]

froide_legalaction/models/lawsuit.py
from datetime import date, timedelta
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from froide.foirequest.models import FoiRequest
from froide.publicbody.models import PublicBody

from .decision import LegalDecision


class CourtTypes(models.TextChoices):
    VG = "VG", _("Administrative Court")
    OVG = "OVG", _("Higher Administrative Court")
    BVerwG = "BVerwG", _("Federal Administrative Court")
    LG = "LG", _("Regional Court")
    OLG = "OLG", _("Higher Regional Court")
    BVerfG = "BVerfG", _("Federal Constitutional Court")
    LVerfG = "LVerfG", _("State Constitutional Court")
    EUG = "EUG", _("European General Court")
    EUGH = "EUGH", _("European Court of Justice")
    EMRK = "EMRK", _("European Court of Human Rights")


class UpcomingTrialsManager(models.Manager):
    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .filter(public=True)
            .annotate(next_end_date=models.Max("instance__end_date"))
            .filter(next_end_date__gte=date.today())
            .order_by("next_end_date")
        )


class Lawsuit(models.Model):
    class Result(models.TextChoices):
        WON = "won", _("won")
        LOST = "lost", _("lost")
        NOT_ACCEPTED = "not_accepted", _("not accepted")
        PARTIALLY_SUCCESSFUL = "partially_successful", _("partially successful")
        SETTLED = "settled", _("settled")

    title = models.CharField(max_length=255, blank=True)
    reference = models.CharField(max_length=255, blank=True)
    description = models.TextField(blank=True)

    last_update = models.DateField(null=True)

    costs = models.DecimalField(null=True, blank=True, decimal_places=2, max_digits=10)
    costs_covered = models.DecimalField(
        null=True, blank=True, decimal_places=2, max_digits=10
    )
    cost_detail = models.TextField(blank=True)

    links = models.TextField(blank=True)

    request = models.ForeignKey(
        FoiRequest, null=True, blank=True, on_delete=models.SET_NULL
    )
    publicbody = models.ForeignKey(
        PublicBody,
        null=True,
        blank=True,
        related_name="defendant_in",
        on_delete=models.SET_NULL,
    )

    plaintiff = models.CharField(max_length=255, blank=True)
    plaintiff_user = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL
    )

    active = models.BooleanField(default=True)
    public = models.BooleanField(default=False)

    result = models.CharField(max_length=20, blank=True, choices=Result.choices)

    objects = models.Manager()
    upcoming = UpcomingTrialsManager()

    class Meta:
        verbose_name = _("lawsuit")
        verbose_name_plural = _("lawsuits")
        ordering = ("-last_update",)

    def __str__(self):
        return self.title

    @property
    def instances(self):
        if not hasattr(self, "_instances"):
            self._instances = list(self.instance_set.all())
        return self._instances

    @property
    def first_instance(self):
        try:
            return self.instances[0]
        except IndexError:
            return None

    @property
    def last_instance(self):
        try:
            return self.instances[-1]
        except IndexError:
            return None

    @property
    def start_date(self):
        return self.first_instance.start_date if self.first_instance else None

    @property
    def end_date(self):
        return self.last_instance.end_date if self.last_instance else None

    @property
    def courts(self):
        return [instance.court for instance in self.instances]

    @property
    def costs_covered_percent(self):
        if self.costs and self.costs_covered:
            return int(self.costs_covered / self.costs * 100)
        return None

    @property
    def costs_deficit(self):
        if self.costs and self.costs_covered:
            return self.costs - self.costs_covered
        return None

    @property
    def needs_money(self):
        if self.costs and self.costs_covered:
            return self.costs_covered < self.costs
        return None

    @property
    def plaintiff_name(self):
        if self.plaintiff_user:
            return self.plaintiff_user.get_full_name()
        return self.plaintiff

    @property
    def result_bootstrap_class(self):
        if self.active:
            return "secondary"
        if self.result in ("won", "partially_successful", "settled"):
            return "success"
        if self.result in ("lost", "not_accepted"):
            return "danger"
        return "secondary"

    @property
    def result_icon(self):
        if self.active:
            return "clock-o"
        if self.result in ("won", "partially_successful", "settled"):
            return "check"
        if self.result in ("lost", "not_accepted"):
            return "times"
        return "clock-o"


class InstanceManager(models.Manager):
    def get_last_three_months(self):
        three_months_ago = timezone.now() - timedelta(days=31 * 3)
        return (
            self.get_queryset()
            .filter(end_date__gte=three_months_ago, lawsuit__public=True)
            .order_by("end_date")
        )


class Instance(models.Model):
    lawsuit = models.ForeignKey(Lawsuit, on_delete=models.CASCADE)

    court_type = models.CharField(max_length=25, choices=CourtTypes.choices, blank=True)
    court = models.ForeignKey(
        PublicBody,
        null=True,
        blank=True,
        related_name="court_public_body",
        on_delete=models.SET_NULL,
    )

    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    result = models.CharField(max_length=20, blank=True, choices=Lawsuit.Result.choices)
    decision = models.ForeignKey(
        LegalDecision, null=True, blank=True, on_delete=models.SET_NULL
    )

    objects = InstanceManager()

    class Meta:
        verbose_name = _("lawsuit")
        verbose_name_plural = _("lawsuits")
        ordering = ("start_date",)

    def __str__(self):
        return "%s (%s): %s" % (self.lawsuit, self.court_type, self.result)

froide_legalaction/templates/froide_legalaction/cms_plugins/next_trials.html
{% load i18n %}
{% if lawsuits|length == 0 %}
    <p class="text-body-secondary">{% trans "There are currently no pending trials." %}</p>
{% else %}
    <ul class="row list-unstyled">
        {% for lawsuit in lawsuits %}
            {% include "froide_legalactions/cms_plugins/trial.html" %}
        {% endfor %}
    </ul>
{% endif %}

froide_legalaction/templates/froide_legalaction/cms_plugins/table.html
{% load markup %}
{% load humanize %}

<div class="lawsuits-table-filter">
  <div class="row">
    <div class="col-md-4">
      <input type="search" placeholder="Suche..." class="form-control" id="lawsuits-search">
    </div>
    <div class="col-md-4">
      <select class="form-select" id="lawsuits-status">
        <option value="all">Status...</option>
        <option value="active">läuft</option>
        {% for result in result_options %}
          <option value="{{ result.0 }}">{{ result.1 }}</option>
        {% endfor %}
      </select>
    </div>

    <div class="col-md-4">
      <select class="form-select" id="lawsuits-court">
        <option value="all">Gericht...</option>
        {% for court in court_options %}
          <option value="{{ court.0 }}">{{ court.1 }}</option>
        {% endfor %}
      </select>
    </div>
  </div>
</div>

<div class="table-responsive lawsuits-table-plugin mt-3">
  <table class="table table-fixed">
    <thead>
      <tr>
        <th><span class="visually-hidden">Status</span></th>
        <th class="topic">Thema</th>
        <th>Eingereicht am</th>
        <th>Gericht</th>
      </tr>
    </thead>
    <tbody>
      <tr class="lawsuit-table-none d-none">
        <td colspan="4" class="text-center py-5">
          <span>Keine Ergebnisse gefunden.</span>
        </td>
      </tr>
      {% for object in object_list %}
        <tr class="lawsuit-table-item" data-pk="{{ object.pk }}" data-status="{% if object.active %}active{% else %}{{ object.result }}{% endif %}" data-court="{{ object.last_instance.court_type }}" data-reference="{{ object.reference }}" id="klage-detail-{{ object.pk }}">
          <td class="text-center">
            <i class="fa fa-{{ object.result_icon }} text-{{ object.result_bootstrap_class }}" data-bs-toggle="tooltip" title="{% if object.active %}läuft{% else %}{{ object.get_result_display }}{% endif %}"></i>
          </td>
          <td class="lawsuit-table-item-title">
            <a href="#klage-detail-{{ object.pk }}" class="d-flex">
              {{ object.title }}
              <span class="small ms-2">
                <i class="fa fa-chevron-down"></i>
              </span>
            </a>
          </td>
          <td>
            {{ object.start_date|date:"SHORT_DATE_FORMAT" }}
          </td>
          <td>
            <abbr title="{{ object.last_instance.court.name }}" data-bs-toggle="tooltip">{{ object.last_instance.court_type }}</abbr>
          </td>
        </tr>
        <tr class="lawsuit-table-details">
          <td></td>
          <td colspan="3">
            <div class="lawsuit-table-details-inner">
              <dl>
                <dt>Eingereicht am</dt>
                <dd>{{ object.start_date }}</dd>

                <dt>Aktenzeichen</dt>
                <dd>{{ object.reference }}</dd>

                <dt>Kläger:in</dt>
                <dd>{{ object.plaintiff }}</dd>

                <dt>Gericht</dt>
                <dd>{{ object.courts | join:", " }}</dd>

                <dt>Termin</dt>
                <dd>{{ object.end_date|default:"unbekannt"}}</dd>

                <dt>Beklagte</dt>
                <dd>{{ object.publicbody.name }}</dd>

                <dt>Anfrage</dt>
                <dd>
                  <a href="{{ object.request.get_absolute_url }}">
                    {{ object.request.title }}
                  </a>
                </dd>

                <dt>Status</dt>
                <dd class="text-{{ object.result_bootstrap_class }}">
                  {% if object.active %}läuft{% else %}{{ object.get_result_display }}{% endif %}
                </dd>
              </dl>

              <div class="my-3 tight-margin text-body">
                {{ object.description | markdown }}
                {{ object.links | markdown }}
              </div>
            </div>
          </dd>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% include "_frontend.html" with entry_point="lawsuits_table.js" %}

froide_legalaction/templates/froide_legalaction/cms_plugins/trial.html
{% load cms_tags %}
{% page_url "lawsuits" as lawsuits_url %}
<li class="col col-12 col-md-4 d-flex mb-2">
    <div class="border border-2 border-gray-300 p-3 w-100">
        <p class="mb-2">
            <a href="{{ lawsuits_url }}#klage-detail-{{ lawsuit.pk }}"
               data-toggle-row
               class="action-link">{{ lawsuit }}</a>
        </p>
        <time datetime="{{ lawsuit.end_date|date:"c" }}">
            <i class="fa fa-calendar me-1"></i> {{ lawsuit.end_date }}
        </time>
        <div>
            <i class="fa fa-legal me-1"></i>
            {{ lawsuit.last_instance.court }}
        </div>
    </div>
</li>